# Generated by Django 3.1.3 on 2020-11-18 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Electronic', 'Electronic'), ('Dairy', 'Dairy'), ('Snack', 'Snack'), ('Other', 'Other')], max_length=20),
        ),
    ]
